alter table public.orders
  add column if not exists payment_method text not null default 'card',
  add column if not exists cash_received_at timestamptz,
  add column if not exists stripe_invoice_id text;

alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders add constraint orders_payment_method_check check (payment_method in ('card', 'cash'));
create unique index if not exists orders_stripe_invoice_id_key on public.orders (stripe_invoice_id) where stripe_invoice_id is not null;

create table if not exists public.specials (
  id bigint generated by default as identity primary key,
  title text not null,
  qualifying_quantity integer not null check (qualifying_quantity between 2 and 100),
  qualifying_unit_price_in_cents integer not null check (qualifying_unit_price_in_cents between 1 and 99999),
  bundle_price_in_cents integer not null check (bundle_price_in_cents between 1 and 999999),
  stripe_product_id text,
  stripe_price_id text,
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint special_is_discount check (bundle_price_in_cents < qualifying_quantity * qualifying_unit_price_in_cents)
);

create unique index if not exists one_active_special on public.specials (is_active) where is_active;
alter table public.specials enable row level security;
revoke all on public.specials from anon, authenticated;
grant select on public.specials to anon, authenticated;
drop policy if exists "Anyone can view the active special" on public.specials;
create policy "Anyone can view the active special" on public.specials for select to anon, authenticated using (is_active);
drop policy if exists "Admins can view all specials" on public.specials;
create policy "Admins can view all specials" on public.specials for select to authenticated using (exists (select 1 from public.admin_users where user_id=auth.uid()));

insert into public.specials(title, qualifying_quantity, qualifying_unit_price_in_cents, bundle_price_in_cents, stripe_price_id)
select '4 Cake Pops for $10', 4, 300, 1000, 'price_1UDYphHSSkrw4MjNQkhoiT7A'
where not exists (select 1 from public.specials where is_active);

alter table public.order_items alter column product_id drop not null;
alter table public.order_items add column if not exists special_id bigint references public.specials(id), add column if not exists stripe_price_id text;

create or replace function public.place_order(customer jsonb, items jsonb)
returns uuid language plpgsql security definer set search_path = '' as $$
declare new_order_id uuid; computed_subtotal integer; requested_payment_method text;
begin
  if jsonb_typeof(items) <> 'array' or jsonb_array_length(items) < 1 or jsonb_array_length(items) > 30 then raise exception 'Order must contain between 1 and 30 items'; end if;
  if char_length(trim(customer->>'name')) not between 2 and 100 then raise exception 'Valid customer name is required'; end if;
  if char_length(trim(customer->>'email')) not between 5 and 254 then raise exception 'Valid email is required'; end if;
  if char_length(trim(customer->>'phone')) not between 7 and 30 then raise exception 'Valid phone is required'; end if;
  if nullif(customer->>'requested_date', '')::date < current_date or nullif(customer->>'requested_date', '') is null then raise exception 'Valid pickup date is required'; end if;
  if coalesce((customer->>'pickup_acknowledged')::boolean, false) is not true then raise exception 'Local pickup must be acknowledged'; end if;
  requested_payment_method := customer->>'payment_method';
  if requested_payment_method not in ('card', 'cash') then raise exception 'Payment method must be card or cash'; end if;

  if exists (select 1 from jsonb_to_recordset(items) as x(product_id bigint,special_id bigint,quantity integer)
    left join public.products p on p.id=x.product_id and p.is_active left join public.specials s on s.id=x.special_id and s.is_active
    where x.quantity not between 1 and 24 or (x.product_id is null)=(x.special_id is null)
      or (x.product_id is not null and p.id is null) or (x.special_id is not null and s.id is null))
  then raise exception 'Order contains an invalid product, special, or quantity'; end if;

  select sum(case when x.product_id is not null then x.quantity*p.price_in_cents else x.quantity*s.bundle_price_in_cents end)::integer into computed_subtotal
  from jsonb_to_recordset(items) as x(product_id bigint,special_id bigint,quantity integer)
  left join public.products p on p.id=x.product_id and p.is_active left join public.specials s on s.id=x.special_id and s.is_active;
  if computed_subtotal is null or computed_subtotal < 1 then raise exception 'Order total is invalid'; end if;

  insert into public.orders(customer_name,customer_email,customer_phone,requested_date,notes,subtotal_in_cents,pickup_acknowledged,fulfillment_method,pickup_address_snapshot,payment_method)
  values(trim(customer->>'name'),lower(trim(customer->>'email')),nullif(trim(customer->>'phone'),''),nullif(customer->>'requested_date','')::date,
    nullif(trim(customer->>'notes'),''),computed_subtotal,true,'local_pickup',null,requested_payment_method) returning id into new_order_id;
  insert into public.order_items(order_id,product_id,special_id,product_title,unit_price_in_cents,quantity,stripe_price_id)
  select new_order_id,p.id,s.id,coalesce(p.title,s.title),coalesce(p.price_in_cents,s.bundle_price_in_cents),x.quantity,s.stripe_price_id
  from jsonb_to_recordset(items) as x(product_id bigint,special_id bigint,quantity integer)
  left join public.products p on p.id=x.product_id and p.is_active left join public.specials s on s.id=x.special_id and s.is_active;
  return new_order_id;
end; $$;
revoke all on function public.place_order(jsonb,jsonb) from public;
grant execute on function public.place_order(jsonb,jsonb) to anon, authenticated;

create or replace function public.record_cash_payment(p_order_id uuid, p_invoice_id text)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  if p_invoice_id !~ '^in_' then raise exception 'Invalid Stripe invoice identifier'; end if;
  update public.orders set status='paid',payment_status='paid',paid_at=now(),cash_received_at=now(),stripe_invoice_id=p_invoice_id,
    pickup_address_snapshot='113 McWhiter Pl, Canton, GA 30115',address_released_at=now(),pickup_time_confirmed=coalesce(pickup_time_confirmed,'Cash received; outside-cart pickup authorized')
  where id=p_order_id and payment_method='cash' and status<>'paid';
  if not found then return false; end if;
  insert into public.pickup_address_access_log(order_id,admin_user_id,release_method) values(p_order_id,null,'cash_payment');
  return true;
end; $$;
revoke all on function public.record_cash_payment(uuid,text) from public,anon,authenticated;
grant execute on function public.record_cash_payment(uuid,text) to service_role;
